### ISSUE TITLE
dual of alt key

### ISSUE THREAD

**Issue by chenzhihuai1990** [lydell/dual#7]
I use the `Alt` as a dual key.
1. when I press `Alt` alone, I hope it act as alt
2.when I press `Alt` with `h``i``j``k`, I hope it act as navigation keys
3.when I press `Alt` with `tab`, I hope it act AltTab to show up switcher.
Do you know any method to implement the  3rd function. 

According to the issue https://github.com/lydell/dual/issues/6, It very hard for me to implement the 3rd one.

**Comment by lydell** [comment]
I'm sorry, but I don't.
